// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5iGAwO-Um9IE99W4LtC-cwflUnSEMdeg',
    appId: '1:1796647747:web:4ed23eb40b39696bd41df6',
    messagingSenderId: '1796647747',
    projectId: 'ai-singing-coach-fdaff',
    authDomain: 'ai-singing-coach-fdaff.firebaseapp.com',
    storageBucket: 'ai-singing-coach-fdaff.firebasestorage.app',
    measurementId: 'G-80GBY4NV9N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_CnZRBf-nh2zED9NRnHoSG34cJNT5aPo',
    appId: '1:1796647747:android:d6f149fa783ba8bcd41df6',
    messagingSenderId: '1796647747',
    projectId: 'ai-singing-coach-fdaff',
    storageBucket: 'ai-singing-coach-fdaff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB87EinXInBQziwD0dYuP0922s1kU7r01s',
    appId: '1:1796647747:ios:2e846ad85b2657e2d41df6',
    messagingSenderId: '1796647747',
    projectId: 'ai-singing-coach-fdaff',
    storageBucket: 'ai-singing-coach-fdaff.firebasestorage.app',
    iosBundleId: 'com.example.aiSingingCoach',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5iGAwO-Um9IE99W4LtC-cwflUnSEMdeg',
    appId: '1:1796647747:web:b48c1de50eaf5fa9d41df6',
    messagingSenderId: '1796647747',
    projectId: 'ai-singing-coach-fdaff',
    authDomain: 'ai-singing-coach-fdaff.firebaseapp.com',
    storageBucket: 'ai-singing-coach-fdaff.firebasestorage.app',
    measurementId: 'G-6G3Z5D0V6T',
  );
}
